Nirma/UIDeviceComplete

- Sources/DeviceFamily.swift
- Sources/DeviceModel.swift
- Sources/Identifier.swift
- Sources/Screen.swift
- Sources/System.swift
- Sources/UIDeviceComplete.swift
- Sources/UIDeviceExtensions.swift
- Tests/DeviceFamilyTests.swift
- Tests/IdentifierTests.swift
- Tests/SystemTests.swift
- Tests/UIDeviceExtensionsTests.swift
- UIDeviceComplete.xcodeproj/project.pbxproj
- UIDeviceComplete/UIDeviceComplete.h
Mostly modernizing settings, silencing warnings and updating the copyright.
> Improvements

- Sources/Identifier.swift
Added iPad Pro 10.5, 2nd gen iPad Pro 12.9, new iPad 5th gen and iPad mini 4
> Added missing iPad model

- Sources/Identifier.swift
- Tests/IdentifierTests.swift
I have never used any of the test stuff in Xcode before, please do check if theres any errors. Mostly copy and pasted.
> Identifier tests

- Sources/Identifier.swift
- Tests/IdentifierTests.swift
Added 6th generation new iPads announced earlier this year.
> iPad 6th Gen Identifiers

- Tests/UIDeviceExtensionsTests.swift
I tried updating the UIDeviceExtensionsTest. I don't really understand XCTests much, so do check if this is acceptable...
> UIDeviceExtensionsTest Updated.

- Sources/DeviceModel.swift
- Sources/Identifier.swift
- Sources/Screen.swift
- Tests/IdentifierTests.swift
- UIDeviceComplete.xcodeproj/project.pbxproj
- Added iPhone XR, iPhone XS and iPhone XS Max to iPhone model
- Update Swift version to 4.2
> Update with fall 2018 devices

- Tests/DeviceModelTests.swift
- UIDeviceComplete.xcodeproj/project.pbxproj
- UIDeviceComplete.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
What do you think? If you think it's good, I'll complete it, and merge it.
> New test for DeviceModel

- Tests/DeviceModelTests.swift
includes all iPhones, iPads and iPod models supported by UIDeviceComplete's DeviceModel
> Added Device model tests

- Sources/DeviceModel.swift
- Sources/Identifier.swift
- Tests/DeviceModelTests.swift
- Tests/IdentifierTests.swift
Added iPad Mini 5 and iPad Air 3
Guess it will be safer to wait awhile before merge to master. The ids may or may not be accurate right now.
> Add new iPads!

- Sources/DeviceModel.swift
- Sources/UIDeviceExtensions.swift
- Tests/DeviceModelTests.swift
- Tests/UIDeviceExtensionsTests.swift
It can be useful to know if the current device has a notch or not. I felt like this belonged in an open source project.
> Add `hasNotch` property

- Sources/DeviceModel.swift
Work In Progress:
- still needs iPad 7th gen
- still needs tests 
- still needs update `Identifier`
> Adding iPhone 11 and friends

- Package.swift
- Sources/Screen.swift
- Sources/System.swift
Updates the swift package file so you can pull in the project with Xcode 11 SPM.
> Update SPM to support Xcode 11

- Sources/DeviceModel.swift
- Sources/Identifier.swift
- Tests/DeviceModelTests.swift
- Tests/IdentifierTests.swift
Have not tested the simulator issue mentioned in #47 though, as I have yet to update Xcode.
> Add iPhone SE 2, new iPad Pros

- Sources/Screen.swift
> Fix 10.2 inch screen size detection

- Sources/DeviceModel.swift
- Sources/Identifier.swift
- Tests/DeviceModelTests.swift
- Tests/IdentifierTests.swift
Adds iPhone 12, mini, Pro, Pro Max device support.
closes #59
> Add new 5G iPhone

- Sources/DeviceModel.swift
- Sources/Identifier.swift
Adds iPhone SE Gen3 & iPod Air Gen 5
> Adds iPhone SE Gen3 & iPod Air Gen 5

- Sources/DeviceModel.swift
- Sources/Identifier.swift
- Tests/DeviceModelTests.swift
- Tests/IdentifierTests.swift
Fixes for iPad Air 5 hardware strings
> Fixes for iPad Air 5 hardware strings & add tests

- UIDeviceComplete.xcodeproj/project.pbxproj
- UIDeviceComplete.xcodeproj/xcshareddata/xcschemes/UIDeviceComplete.xcscheme
Simply just silence warnings related to project file.
> Modernize project settings.

- Sources/Identifier.swift
iPad 10th gen, iPad Pro 11 4th Gen, iPad Pro 12.9 6th Gen
> Updates for 10.2022 iPads

- Sources/DeviceModel.swift
iPad 10th gen, iPad Pro 11 4th Gen, iPad Pro 12.9 6th Gen
> Updates for New iPads 10/2022

- Sources/DeviceFamily.swift
- Sources/UIDeviceExtensions.swift
Update  to use targentEnv instead of older swift 3 method.
> Update  to use targentEnv instead of older swift 3 method.
